name: Release
on:
  release:
    types: [published]

jobs:
  publish:
    name: Deploy Release to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: 3.7
      - name: Install dependencies
        run: pip install twine
      - name: Build package
        run: python setup.py sdist
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
      - name: Install tox
        run: pip install tox
      - name: Generate API docs
        run: |
          rm -rf ./docs/_build
          tox -e docs
      - name: Docs Upload
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: python_sdk_docs
          path: docs/_build/html
      # Test upload
      # - name: Publish package to TestPyPI
      #   uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc
      #   with:
      #     user: __token__
      #     password: ${{ secrets.test_pypi_password }}
      #     repository_url: https://test.pypi.org/legacy/
